# Generated by Django 5.0 on 2024-02-28 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vivero', '0002_producto_descripcion_producto_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orden',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='direccionenvio',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='direccionenvio',
            name='orden',
        ),
        migrations.RemoveField(
            model_name='ordenitem',
            name='orden',
        ),
        migrations.RemoveField(
            model_name='ordenitem',
            name='producto',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='digital',
        ),
        migrations.AlterField(
            model_name='producto',
            name='descripcion',
            field=models.CharField(default='Descripción del producto', max_length=500),
        ),
        migrations.DeleteModel(
            name='Cliente',
        ),
        migrations.DeleteModel(
            name='DireccionEnvio',
        ),
        migrations.DeleteModel(
            name='Orden',
        ),
        migrations.DeleteModel(
            name='OrdenItem',
        ),
    ]
