# Generated by Django 5.0 on 2024-02-28 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vivero', '0003_remove_orden_cliente_remove_direccionenvio_cliente_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuienesSomos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_columna', models.CharField(max_length=100)),
                ('texto_columna', models.CharField(default='Texto de columna de sección Quiénes somos', max_length=500)),
                ('imagen_columna', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
