# Generated by Django 5.0 on 2024-02-28 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vivero', '0004_quienessomos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrusel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen_carrusel', models.ImageField(blank=True, null=True, upload_to='')),
                ('frase_carrusel', models.CharField(default='Frase de imagen del carrusel', max_length=100)),
            ],
        ),
    ]
