# Generated by Django 5.0 on 2024-02-29 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vivero', '0005_carrusel'),
    ]

    operations = [
        migrations.CreateModel(
            name='FraseInicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frase', models.CharField(default='Frase principal', max_length=50)),
                ('imagen_inicio', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
