# Generated by Django 5.0 on 2024-02-29 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vivero', '0006_fraseinicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fraseinicio',
            name='imagen_inicio',
            field=models.ImageField(blank=True, null=True, upload_to='frase_inicio/'),
        ),
    ]
